<!DOCTYPE html>
<html>
    <head>
        <title>Football Management Website</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <?php   
            include($CSS_PATH);
        ?>
    </head>
    <body>
        <div class="pushDownContent">header</div>
        <div id="header">
            <?php include($HEADER_PATH);?>
        </div>              
        <div id="banner"></div>        
        <div id="wrapper">   
            <div id="smallbar"></div> 
            <div id="content">                    
                <?php include($CONTENT_PATH);?>
            </div>   
        </div>
        <div class="pushUpContent">footer</div>
        <div id="footer">
                <?php include($FOOTER_PATH);?>
        </div>   
        <!-- Messenger Chat plugin Code -->
        <div id="fb-root"></div>

        <!-- Your Chat plugin code -->
        <div id="fb-customer-chat" class="fb-customerchat">
        </div>

        <script>
            var chatbox = document.getElementById('fb-customer-chat');
            chatbox.setAttribute("page_id", "103849619026102");
            chatbox.setAttribute("attribution", "biz_inbox");
        </script>

        <!-- Your SDK code -->
        <script>
            window.fbAsyncInit = function () {
                FB.init({
                    xfbml: true,
                    version: 'v14.0'
                });
            };

            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/vi_VN/sdk/xfbml.customerchat.js';
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
    </body>
</html>