<style>
    table.searchPlayerTableInput,
    table.searchPlayerTableInput th,
    table.searchPlayerTableInput td,
    table.searchPlayerTableInput tr {
        border: 0;
    }

    .alignAdvancedSearchButton {
        text-align: end;
    }

    .advancedSearch {
        border: 2px solid rgb(131, 188, 237);
        padding: 10px;
        margin-top: 10px;
        margin-bottom: 10px;
        border-radius: 2px;
    }
    #searchPlayerTable{
        border: 2px solid rgb(131, 188, 237);
        padding: 10px;
        margin-top: 10px;
        margin-bottom: 10px;
        border-radius: 2px;
    }
</style>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $('#advancedSearchButton').click(function () {
            let playerName = encodeURI($('#playerNameInput').val());
            let playerPosition = encodeURI($('#playerPositionInput').val());
            let playerClub = encodeURI($('#playerClubInput').val());
            let playerNumber = encodeURI($('#playerNumberInput').val());
            let playerNationality = encodeURI($('#playerNationalityInput').val());
            let url = 'http://localhost/18120418_Football/components/getAllPlayerClub.php?action=searchPlayerAdvanced';
            let data = {
                playerName,
                playerPosition,
                playerClub,
                playerNumber,
                playerNationality
            };
            $.ajax({
                url,
                type: 'POST',
                data,
                async: true,
                success: function (data) {
                    $('#searchPlayerTable').html(data);
                }
            });
        });
    });
</script>

<div class="advancedSearch">
    <table class="searchPlayerTableInput">
        <caption>Advanced Search</caption>
        <tr>
            <th>Name:</th>
            <td><input type="text" id="playerNameInput"></td>
        </tr>
        <tr>
            <th>Position:</th>
            <td><input type="text" id="playerPositionInput"></td>
        </tr>
        <tr>
            <th>Club:</th>
            <td><input type="text" id="playerClubInput"></td>
        </tr>
        <tr>
            <th>Number:</th>
            <td><input type="text" id="playerNumberInput"></td>
        </tr>
        <tr>
            <th>Nationality:</th>
            <td><input type="text" id="playerNationalityInput"></td>
        </tr>
        <tr>
            <th></th>
            <td class="alignAdvancedSearchButton"><input type="button" value="Advanced Search"
                    id="advancedSearchButton"></td>
        </tr>
    </table>
</div>